"""Agent Metrics Demo - Agno Framework Implementation

This module demonstrates Agno's built-in metrics and monitoring capabilities
for tracking agent performance, token usage, and tool calls.

About Agno Metrics:
    Agno automatically tracks:
    - Token usage per message and per run
    - Cost estimation based on model pricing
    - Tool call statistics
    - Response times and latency
    - Message-level and session-level aggregations
    
About OpenAI Integration:
    Uses OpenAI's GPT-4o model via Agno wrapper.
    - Excellent tool calling support
    - Detailed metrics tracking
    - Reliable function calling
    
Tools Used:
    YFinanceTools: Real-time stock market data from Yahoo Finance
    - Stock prices
    - Historical data
    - Company information
    
Environment Setup:
    Requires OPENAI_API_KEY in .env file or environment variables.
    
Usage:
    python agents/AgentMetrics.py
"""

from typing import Iterator

from agno.agent import Agent, RunResponse
from agno.models.openai import OpenAIChat
from agno.tools.yfinance import YFinanceTools
from rich.pretty import pprint

from dotenv import load_dotenv
load_dotenv()  # Load environment variables from .env file


def main():
    """Main function to run the Agent Metrics demo.
    
    This function demonstrates:
    - Creating an agent with metrics tracking enabled
    - Making queries and getting responses
    - Accessing per-message metrics
    - Accessing run-level metrics
    - Accessing session-level metrics
    
    Metrics tracked by Agno:
    - input_tokens: Tokens sent to the model
    - output_tokens: Tokens generated by the model
    - total_tokens: Sum of input and output tokens
    - time_to_first_token: Latency before first response token
    - response_time: Total time for the response
    - estimated_cost: Calculated based on model pricing
    """
    print("=== Agent Metrics Demo ===")
    print("This demo shows Agno's built-in metrics tracking capabilities.\n")
    
    # Initialize Agno Agent with metrics tracking
    # Agno automatically captures metrics for every interaction
    # Using OpenAI's GPT-4o for reliable tool calling and metrics
    agent = Agent(
        model=OpenAIChat(id="gpt-4o"),  # OpenAI's GPT-4o with excellent tool support
        tools=[YFinanceTools(stock_price=True)],  # Yahoo Finance integration
        markdown=True,
        show_tool_calls=True,  # Display when tools are called
    )
    
    # Get stock symbol from user
    stock_symbol = input("Enter stock symbol (or press Enter for default 'NVDA'): ").strip().upper()
    
    if not stock_symbol:
        stock_symbol = "NVDA"
        print(f"\nUsing default stock symbol: {stock_symbol}\n")
    else:
        print(f"\nQuerying stock price for: {stock_symbol}\n")
    
    # Run the agent with the query
    # Agno tracks metrics automatically during execution
    agent.print_response(
        f"What is the stock price of {stock_symbol}", stream=True
    )
    
    print("\n" + "="*60)
    print("METRICS ANALYSIS")
    print("="*60 + "\n")
    
    # Print metrics per message
    # Each message in the conversation has its own metrics
    if agent.run_response.messages:
        print("--- Per-Message Metrics ---\n")
        for i, message in enumerate(agent.run_response.messages, 1):
            if message.role == "assistant":
                print(f"Message #{i}:")
                if message.content:
                    print(f"Content: {message.content[:100]}...")
                elif message.tool_calls:
                    print(f"Tool calls: {message.tool_calls}")
                print("\n" + "---" * 5 + " Metrics " + "---" * 5)
                pprint(message.metrics)
                print("---" * 20 + "\n")
    
    # Print the aggregated metrics for the whole run
    # Run metrics aggregate all messages in the current query
    print("\n" + "---" * 5 + " Run Metrics (Current Query) " + "---" * 5)
    pprint(agent.run_response.metrics)
    print("---" * 20 + "\n")
    
    # Print the aggregated metrics for the whole session
    # Session metrics aggregate all runs since agent was created
    print("---" * 5 + " Session Metrics (All Queries) " + "---" * 5)
    pprint(agent.session_metrics)
    print("---" * 20)
    
    print("\n✓ Metrics tracking complete!")
    print("\nKey Insights:")
    print("- Per-message metrics show individual API calls")
    print("- Run metrics show totals for current query")
    print("- Session metrics accumulate across all interactions")


if __name__ == "__main__":
    main()